{
 "title": "Diameter DCCA Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(erlang_vm_process_count, instance)"
    }
   },
   {
    "name": "diameter_service",
    "label": "Diameter Service",
    "query": {
     "query": "label_values(diameter_applications, svc)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Diameter Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "diameter_applications{svc=\"$diameter_service\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[30s])) without (kind) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}"
    }
   ]
  },
  { "title": "Diameter Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "diameter_service" },
  {
   "title": "Application Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "diameter_applications", "legendFormat": "{{svc}}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(diameter_connections{svc=\"$diameter_service\"})"
    }
   ]
  },
  {
   "title": "Diameter ResultCodes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rc) (diameter_messages{rc!=\"\"})",
     "legendFormat": "{{rc}}"
    }
   ]
  },
  {
   "title": "MSCC Interrogation by type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dcca_mscc_interrogation{svc=\"$diameter_service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Diameter Messages",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "diameter_messages", "legendFormat": "{{msg}}" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Diameter Errors for current application",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diameter_errors{svc=\"$diameter_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diameter Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diameter_messages{svc=\"$diameter_service\"}[1m])",
     "legendFormat": "Diameter {{direction}} {{msg}}"
    }
   ]
  },
  {
   "title": "MSCC Interrogations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dcca_mscc_interrogation{svc=\"$diameter_service\"}[1m]))",
     "legendFormat": "MSCC Rate"
    },
    {
     "expr": "rate(dcca_mscc_interrogation{svc=\"$diameter_service\", type=\"first\"}[1m])",
     "legendFormat": "MSCC First Interrogation Rate"
    },
    {
     "expr": "rate(dcca_mscc_interrogation{svc=\"$diameter_service\", type=\"next\"}[1m])",
     "legendFormat": "MSCC Next Interrogation Rate"
    },
    {
     "expr": "rate(dcca_mscc_interrogation{svc=\"$diameter_service\", type=\"last\"}[1m])",
     "legendFormat": "MSCC Last Interrogation Rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
       "legendFormat": "Processes Memory"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
       "legendFormat": "Atoms"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
       "legendFormat": "Binary"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
       "legendFormat": "Code"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
       "legendFormat": "ETS"
      }
     ]
    },
    {
     "title": "OS Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"$node\"}",
       "legendFormat": "Resident Memory"
      }
     ]
    },
    {
     "title": "VM GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[5m])",
       "legendFormat": "Number of GCs"
      },
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[5m])",
       "legendFormat": "Bytes Reclaimed"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Native Threads & CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "process_threads_total{instance=\"$node\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[30s])) without (kind) * 100",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[5m])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[5m])",
       "legendFormat": "Reductions"
      },
      {
       "expr": "irate(erlang_vm_statistics_runtime_milliseconds{instance=\"$node\"}[5m])",
       "legendFormat": "Runtime"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[5m])",
       "legendFormat": "Output Bytes"
      },
      {
       "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[5m])",
       "legendFormat": "Received Bytes"
      }
     ]
    },
    {
     "title": "VM IO Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_statistics_bytes_received_total{instance=\"$node\"}",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "erlang_vm_statistics_bytes_output_total{instance=\"$node\"}",
       "legendFormat": "Sent Bytes"
      }
     ]
    },
    {
     "title": "File Descriptors & Ports",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"}",
       "legendFormat": "Open FDs"
      },
      {
       "expr": "process_max_fds{instance=\"$node\"}",
       "legendFormat": "Max FDs"
      },
      {
       "expr": "erlang_vm_port_limit{instance=\"$node\"}",
       "legendFormat": "Max Ports"
      },
      {
       "expr": "erlang_vm_port_count{instance=\"$node\"}",
       "legendFormat": "Ports"
      }
     ]
    }
   ]
  },
  {
   "title": "Erlang Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Duration",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "telemetry_scrape_duration_seconds",
       "legendFormat": "scrape time"
      }
     ]
    },
    {
     "title": "ETS/DETS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_ets_limit{instance=\"$node\"}",
       "legendFormat": "ETS Limit"
      },
      {
       "expr": "erlang_vm_memory_ets_tables{instance=\"$node\"}",
       "legendFormat": "ETS Tables"
      },
      {
       "expr": "erlang_vm_memory_dets_tables{instance=\"$node\"}",
       "legendFormat": "DETS Tables"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_process_count{instance=\"$node\"}",
       "legendFormat": "Processes"
      },
      {
       "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
       "legendFormat": "Run Queues Length"
      }
     ]
    },
    {
     "title": "Atoms",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_atom_count{instance=\"$node\"}",
       "legendFormat": "Atoms"
      }
     ]
    }
   ]
  }
 ]
}