-define(DCCA_APPLICATION_ID, 4).
-define(DIAMETER_IP, "127.0.0.1").
-define(DIAMETER_PORT, 3868).
-define(DIAMETER_PROTO, tcp).
-define(VENDOR_ID, 0).
-define(ORIGIN_HOST, "example.com").
-define(ORIGIN_REALM, "realm.example.com").
-define(CONTEXT_ID, "gprs@diameter.com").

-define(CCR_INITIAL, ?'RFC4006_CC_GY_CC-REQUEST-TYPE_INITIAL_REQUEST').
-define(CCR_UPDATE, ?'RFC4006_CC_GY_CC-REQUEST-TYPE_UPDATE_REQUEST').
-define(CCR_TERMINATE, ?'RFC4006_CC_GY_CC-REQUEST-TYPE_TERMINATION_REQUEST').

-define(MSISDN, ?'RFC4006_CC_GY_SUBSCRIPTION-ID-TYPE_END_USER_E164').
-define(IMSI, ?'RFC4006_CC_GY_SUBSCRIPTION-ID-TYPE_END_USER_IMSI').
